language: php
php:
  - 7.1
  - 7.2

env:
  - WP_VERSION="4.9.9"
  - WP_VERSION="5.0.0"
  - WP_VERSION="5.0.3"

install:
  - composer install

before_script:
  - export WP_TESTS_DIR=/tmp/wp-tests
  - svn checkout http://develop.svn.wordpress.org/tags/${WP_VERSION} ${WP_TESTS_DIR}
  - mysql -e 'CREATE DATABASE test_db;'
  - cp ${WP_TESTS_DIR}/wp-tests-config-sample.php ${WP_TESTS_DIR}/wp-tests-config.php
  - sed -i 's/youremptytestdbnamehere/test_db/' ${WP_TESTS_DIR}/wp-tests-config.php
  - sed -i 's/yourusernamehere/root/' ${WP_TESTS_DIR}/wp-tests-config.php
  - sed -i 's/yourpasswordhere//' ${WP_TESTS_DIR}/wp-tests-config.php

script: ./vendor/bin/phpunit --coverage-clover=clover.xml -c ./tests/phpunit.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9bb02c429968e213a35f
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never