name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - quodana
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.1.1